export type ModelItem = {
  model: string;
  icon?: string;
  disabled?: boolean;
};

const models: ModelItem[] = [
  { model: 'adirik/realvisxl-v3.0-turbo', icon: '/adirik.jpg', disabled: true },
  { model: 'ai-forever/kandinsky-2', icon: '/ai-forever.jpg', disabled: true },
  { model: 'ai-forever/kandinsky-2.2', icon: '/ai-forever.jpg', disabled: true },
  { model: 'black-forest-labs/flux-1.1-pro', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-1.1-pro-ultra', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-dev', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-dev-lora', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-kontext-max', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-kontext-pro', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-pro', icon: '/black-forest-labs.png' },
  { model: 'black-forest-labs/flux-schnell', icon: '/black-forest-labs.png' },
  { model: 'bria/image-3.2', icon: '/bria.png' },
  { model: 'bytedance/seedream-3', icon: '/bytedance.png', disabled: true },
  { model: 'bytedance/seedream-4', icon: '/bytedance.png' },
  { model: 'bytedance/sdxl-lightning-4step', icon: '/bytedance.png' },
  { model: 'datacte/proteus-v0.3', icon: '/detacte.jpg', disabled: true },
  { model: 'fermatresearch/sdxl-controlnet-lora', icon: '/fermatresearch.png', disabled: true },
  { model: 'fofr/any-comfyui-workflow', icon: '/fofr.jpg', disabled: true },
  { model: 'fofr/latent-consistency-model', icon: '/fofr.jpg', disabled: true },
  { model: 'fofr/realvisxl-v3-multi-controlnet-lora', icon: '/fofr.jpg', disabled: true },
  { model: 'fofr/sdxl-emoji', icon: '/fofr.jpg', disabled: true },
  { model: 'fofr/sdxl-multi-controlnet-lora', icon: '/fofr.jpg', disabled: true },
  { model: 'fofr/sticker-maker', icon: 'fofr.jpg', disabled: true },
  { model: 'google/imagen-3', icon: '/google.png' },
  { model: 'google/imagen-3-fast', icon: '/google.png' },
  { model: 'google/imagen-4', icon: '/google.png' },
  { model: 'google/imagen-4-fast', icon: '/google.png' },
  { model: 'google/imagen-4-ultra', icon: '/google.png' },
  { model: 'google/nano-banana', icon: '/google.png' },
  { model: 'ideogram-ai/ideogram-v2', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v2-turbo', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v2a', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v2a-turbo', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v3-balanced', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v3-quality', icon: '/ideogram-ai.png' },
  { model: 'ideogram-ai/ideogram-v3-turbo', icon: '/ideogram-ai.png' },
  { model: 'jagilley/controlnet-scribble', icon: '/jagilley.png', disabled: true },
  { model: 'leonardoai/lucid-origin', icon: '/leonardo-ai.jpg', disabled: true },
  { model: 'lucataco/dreamshaper-xl-turbo', icon: '/lucataco.jpg', disabled: true },
  { model: 'lucataco/open-dalle-v1.1', icon: '/lucataco.jpg', disabled: true },
  { model: 'lucataco/realistic-vision-v5.1', icon: '/lucataco.jpg', disabled: true },
  { model: 'lucataco/ssd-1b', icon: '/lucataco.jpg', disabled: true },
  { model: 'luma/photon', icon: '/luma.png', disabled: true },
  { model: 'luma/photon-flash', icon: '/luma.png' },
  { model: 'minimax/image-01', icon: '/minimax.png' },
  { model: 'nvidia/sana', icon: '/nvidia.png', disabled: true },
  { model: 'nvidia/sana-sprint-1.6b', icon: '/nvidia.png', disabled: true },
  {
    model: 'playgroundai/playground-v2.5-1024px-aesthetic',
    icon: '/playgroundai.png',
    disabled: true,
  },
  { model: 'prunaai/flux.1-dev', icon: '/prunaai.png', disabled: true },
  { model: 'prunaai/hidream-l1-dev', icon: '/prunaai.png', disabled: true },
  { model: 'prunaai/hidream-l1-fast', icon: '/prunaai.png', disabled: true },
  { model: 'prunaai/hidream-l1-full', icon: '/prunaai.png', disabled: true },
  { model: 'prunaai/sdxl-lightning', icon: '/prunaai.png', disabled: true },
  { model: 'prunaai/wan-2.2-image', icon: '/prunaai.png' },
  { model: 'qwen/qwen-image', icon: '/qwen.jpg' },
  { model: 'recraft-ai/recraft-v3', icon: '/recraft-ai.png' },
  { model: 'recraft-ai/recraft-v3-svg', icon: '/recraft-ai.png' },
  { model: 'stability-ai/sdxl', icon: '/stability-ai.png', disabled: true },
  { model: 'stability-ai/stable-diffusion', icon: '/stability-ai.png', disabled: true },
  { model: 'stability-ai/stable-diffusion-3.5-large', icon: '/stability-ai.png' },
  { model: 'stability-ai/stable-diffusion-3.5-large-turbo', icon: '/stability-ai.png' },
  { model: 'stability-ai/stable-diffusion-3.5-medium', icon: '/stability-ai.png' },
  { model: 'tencent/hunyuan-image-3', icon: '/tencent.png' },
  { model: 'tstramer/material-diffusion', icon: '/tstramer.png', disabled: true },
];

export default models;
